language: elixir
elixir:
  - 1.9.1
otp_release:
  - 22.0.7
env:
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - mat@geeky.net
